services:
  mysql:
    image: mysql:8.0
    container_name: cgv_clone_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppw
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: cgv_clone_myredis
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    image: immmii/cgv-clone:latest
    container_name: test
    platform: linux/amd64
    ports:
      - "8080:8080"
    env_file: ./src/main/resources/local.env
    depends_on:
      - mysql
      - redis
    restart: unless-stopped